blank_issues_enabled: false
contact_links:
  - name: Emacs StackExchange
    url: https://emacs.stackexchange.com/questions/tagged/magit
    about: Please search, ask and answer questions here.
  - name: Emacs Reddit
    url: https://www.reddit.com/r/emacs
    about: Another place to ask questions.
  - name: FAQ
    url: https://magit.vc/manual/faq.html
    about: It might be that many others had the same question.
  - name: Manuals
    url: https://magit.vc/manual
    about: The fine manuals may also be of use.
